version: '2'

services:
    nexus:
        container_name: nexus
        image: sonatype/nexus3
        ports:
            - "8081"
        expose:
            - "8081"
        volumes:
            - nexus-data:/nexus-data
volumes:
    nexus-data:
